/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kcamlhrwbjskzsykisar";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYW1saHJ3Ympza3pzeWtpc2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNzU5NDMsImV4cCI6MjA3NDg1MTk0M30.NQX23nhyoEptcIT3dMqlO1HfB2mpg9Am6nHHpoQYhcA";
